In [7]:
import matplotlib as mpl
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [8]:
df = pd.read_csv('salesweekly.csv')

In [9]:
df

          datum  M01AB   M01AE  N02BA    N02BE  N05B  N05C        R03    R06
0      1/5/2014  14.00  11.670  21.30  185.950  41.0   0.0  32.000000   7.00
1     1/12/2014  29.33  12.680  37.90  190.700  88.0   5.0  21.000000   7.20
2     1/19/2014  30.67  26.340  45.90  218.400  80.0   8.0  29.000000  12.00
3     1/26/2014  34.00  32.370  31.50  179.600  80.0   8.0  23.000000  10.00
4      2/2/2014  31.02  23.350  20.70  159.880  84.0  12.0  29.000000  12.00
..          ...    ...     ...    ...      ...   ...   ...        ...    ...
297   9/15/2019  35.51  30.977  19.65  178.375  67.2   5.0  30.000000  30.50
298   9/22/2019  46.84  25.396  24.40  248.250  31.2   3.0  26.000000  21.00
299   9/29/2019  34.01  22.498  26.60  336.700  61.2   1.0  40.416667  23.10
300   10/6/2019  38.70  32.502  19.25  249.450  69.0   5.0  30.000000  12.13
301  10/13/2019   7.67   6.237   3.50   95.100  26.0   2.0  12.000000   1.00

[302 rows x 9 columns]

In [4]:
df.isnull()

     datum  M01AB  M01AE  N02BA  N02BE   N05B   N05C    R03    R06
0    False  False  False  False  False  False  False  False  False
1    False  False  False  False  False  False  False  False  False
2    False  False  False  False  False  False  False  False  False
3    False  False  False  False  False  False  False  False  False
4    False  False  False  False  False  False  False  False  False
..     ...    ...    ...    ...    ...    ...    ...    ...    ...
297  False  False  False  False  False  False  False  False  False
298  False  False  False  False  False  False  False  False  False
299  False  False  False  False  False  False  False  False  False
300  False  False  False  False  False  False  False  False  False
301  False  False  False  False  False  False  False  False  False

[302 rows x 9 columns]

In [10]:
date_time = pd.to_datetime(df.pop('datum'), format='%m/%d/%Y')
df.head()

   M01AB  M01AE  N02BA   N02BE  N05B  N05C   R03   R06
0  14.00  11.67   21.3  185.95  41.0   0.0  32.0   7.0
1  29.33  12.68   37.9  190.70  88.0   5.0  21.0   7.2
2  30.67  26.34   45.9  218.40  80.0   8.0  29.0  12.0
3  34.00  32.37   31.5  179.60  80.0   8.0  23.0  10.0
4  31.02  23.35   20.7  159.88  84.0  12.0  29.0  12.0

In [12]:
sales_rate = np.zeros((len(df), ))
df['sales_rate'] = sales_rate


high_sales = 1.0
low_sales = 0.0

column_list = list(df)
for index, row in df.iterrows():
    total_sales = row.sum()
    #print(row)
    if total_sales > 400:
        df.at[index, 'sales_rate'] = high_sales

#drop the sales_rate column and make it the target data
target = df.pop('sales_rate')
print(target.head())

0    0.0
1    0.0
2    1.0
3    0.0
4    0.0
Name: sales_rate, dtype: float64

In [ ]:
mpl.rcParams['figure.figsize'] = (16, 16)
plot_cols = ['M01AB', 'M01AE', 'N02BA', 'N02BE', 'N05B', 'N05C', 'R03', 'R06']
plot_features = df[plot_cols]
_ = plot_features.plot(subplots=True)
p